plugins {
	id 'java'
	id 'com.diffplug.spotless' version '8.10.1'
	id 'io.spring.dependency-management' version '1.1.7'
	id 'org.springframework.boot' version '4.1.1'
}

group = 'com.aranlucas'
version = '1.0.0-SNAPSHOT'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(21)
	}
}

repositories {
	mavenCentral()
}

dependencies {
	developmentOnly 'org.springframework.boot:spring-boot-devtools'
	implementation 'org.flywaydb:flyway-core'
	implementation 'org.flywaydb:flyway-database-postgresql'
	implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:3.1.0'
	implementation 'org.springframework.boot:spring-boot-starter-actuator'
	implementation 'org.springframework.boot:spring-boot-starter-cache'
	implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
	implementation 'org.springframework.boot:spring-boot-starter-data-redis'
	implementation 'org.springframework.boot:spring-boot-starter-oauth2-client'
	implementation 'org.springframework.boot:spring-boot-starter-validation'
	implementation 'org.springframework.boot:spring-boot-starter-web'
	implementation 'org.springframework.modulith:spring-modulith-starter-core'
	runtimeOnly 'org.postgresql:postgresql'
	testImplementation 'org.springframework.boot:spring-boot-data-jpa-test'
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testImplementation 'org.springframework.modulith:spring-modulith-starter-test'
	testRuntimeOnly 'com.h2database:h2'
}

dependencyManagement {
	imports {
		mavenBom 'org.springframework.modulith:spring-modulith-bom:2.1.1'
	}
}

springBoot {
	buildInfo()
}

tasks.named('bootJar') {
	archiveFileName = 'spring-todo-api.jar'
}

tasks.named('jar') {
	enabled = false
}

tasks.named('test') {
	useJUnitPlatform()
}

spotless {
	format 'misc', {
		target '*.gradle', '*.properties', '*.toml', '*.yml', '.gitignore'
		trimTrailingWhitespace()
		endWithNewline()
	}
	format 'markdown', {
		target 'README.md', 'docs/**/*.md'
		trimTrailingWhitespace()
		endWithNewline()
	}
	java {
		importOrder()
		removeUnusedImports()
		cleanthat()
		googleJavaFormat().aosp()
		formatAnnotations()
	}
}
